---
galaxy_info:
  role_name: nginx
  author: "Sinu Nimi"
  description: "Nginx web server for multiple environments (dev/staging/prod)"
  company: "IT College"
  license: MIT
  min_ansible_version: "2.9"
  
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
  
  galaxy_tags:
    - web
    - nginx
    - multienv

dependencies: []
